### ISSUE TITLE
Data Table Enhancements

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#168]
- [x] Allow selecting what columns are visible for atlas/biospecimen/case/files tab (#181)
- [x] For biospecimen and cases tab we can use the data model to figure out what all the required and optional columns are. We could e.g. show all required columns by default (#216)
- [x] Enable search like on the Files tab, but for all columns (similar to mutations table in cBioPortal). Again for all of atlas/biospecimen/case/files tab (#187)
